<a href="https://colab.research.google.com/github/Satyajit1512/DeepLearningWithPython/blob/main/IntroductoryNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from tensorflow.keras.datasets import mnist

In [3]:
(training_images, train_labels), (test_images,test_labels) = mnist.load_data()

In [12]:
# checking a data

training_images[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 170,
        253, 253, 253, 253, 253, 225, 172, 253, 242, 195,  64,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,  49, 238, 253, 253, 253, 253,
        253, 253, 253, 253, 251,  93,  82,  82,  56,  39,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,  18, 219, 253, 253, 253, 253,
        253, 198, 182, 247, 241,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  80, 156, 107, 253, 253,
        205,  11,   0,  43, 154,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,  14,   1, 154, 253,
         90,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 139, 253,
        190,   2,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  11, 190,
        253,  70,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  35,
        241, 225, 160, 108,   1,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         81, 240, 253, 253, 119,  25,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,  45, 186, 253, 253, 150,  27,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,  16,  93, 252, 253, 187,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0, 249, 253, 249,  64,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,  46, 130, 183, 253, 253, 207,   2,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  39,
        148, 229, 253, 253, 253, 250, 182,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  24, 114, 221,
        253, 253, 253, 253, 201,  78,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  23,  66, 213, 253, 253,
        253, 253, 198,  81,   2,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,  18, 171, 219, 253, 253, 253, 253,
        195,  80,   9,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,  55, 172, 226, 253, 253, 253, 253, 244, 133,
         11,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0, 136, 253, 25

In [14]:
train_labels[0]

5

In [6]:
training_images.shape

(60000, 28, 28)

In [7]:
len(training_images)

60000

In [28]:
len(test_images)

10000

In [19]:
from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential([
    layers.Dense(512, activation = "relu"),
    layers.Dense(10, activation = "softmax")
])

In [29]:
model.compile(optimizer = "rmsprop",
              loss = "sparse_categorical_crossentropy",
              metrics = ["accuracy"])

In [32]:
train_images = training_images.reshape((60000, 28*28))
train_images = train_images.astype("float32")/255
test_images = test_images.reshape((10000, 28*28))
test_images = test_images.astype("float32")/255

In [36]:
model.fit(train_images, train_labels, epochs = 5 , batch_size = 128)

Epoch 1/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.8740 - loss: 0.4414
Epoch 2/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - accuracy: 0.9650 - loss: 0.1230
Epoch 3/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - accuracy: 0.9772 - loss: 0.0739
Epoch 4/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 0.9842 - loss: 0.0532
Epoch 5/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - accuracy: 0.9887 - loss: 0.0382


In [37]:
test_digits = test_images[:10]

In [38]:
predictions = model.predict(test_digits)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step


In [39]:
predictions[0]

array([0.05604381, 0.10927168, 0.09351338, 0.06036495, 0.09745874,
       0.23702617, 0.08880222, 0.11190221, 0.06590765, 0.07970916],
      dtype=float32)

In [40]:
predictions[0].argmax()

5

In [43]:
predictions[0]

array([0.05604381, 0.10927168, 0.09351338, 0.06036495, 0.09745874,
       0.23702617, 0.08880222, 0.11190221, 0.06590765, 0.07970916],
      dtype=float32)

In [44]:
test_loss, test_acc = model.evaluate(test_images, test_labels)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0912 - loss: 2.3893


In [45]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [46]:
import tensorflow as tf

x = tf.Variable(0.)

with tf.GradientTape() as tape:

  y = 2*x + 3

grad_of_y_wrt_x = tape.gradient(y, x)

In [48]:
import tensorflow as tf

class NaiveDense:
  def __init__(self, input_size, output_size, activation):
      self.activation = activation
      w_shape = (input_size, output_size)
      w_initial_value = tf.random.uniform(w_shape, min_val = 0.0, maxval = 1e-1)
      self.W = tf.Variable(w_initial_value)

      b_shape = output_size,
      b_initial_value = tf.zeros(b_shape)
      self.b = tf.Variable(b_initial_value)

  def __call__(self, inputs):
    return self.activation(tf.matmul(inputs, self.W) + self.b)

  @property
  def weights(self):
    return [self.W, self.b]


In [ ]:
class NaiveSequential:
    def __init__(self):
      self.layers = layers

    def __call__(self, inputs):
      x = inputs
      for layer in self.layers:
        x = layer(x)
      return x

    @property
    def weights(self):
      weights = []
      for layer in self.layers:
        weights += self.weights
      return weights


In [49]:
import math

class BatchGenerator:
  def __init__(self, images, labels, batch_size = 128):
    self.index = 0
    self.images = images
    self.labels = labels
    self.batch_size = batch_size
    self.num_batches = math.ceil(len(images)/batch_size)

  def next(self):
    images = self.images[self.index : self.index + self.batch_size]
    labels = self.labels[self.index : self.index + self.batch_size]
    self.index += self.batch_size
    return images, labels


In [55]:
def one_training_step(model, images_batch, labels_batch):
  with tf.GradientTape() as tape:
    predictions = model(images_batch)
    per_sample_losses = tf.keras.losses.sparse_categorical_crossentropy(labels_batch, predictions)
    average_loss = tf.reduce_mean(per_sample_losses)

  gradients = tape.gradient(average_loss, model.weights)
  update_weights(gradients, model.weights)
  return average_loss


In [56]:
learning_rate = 1e-3
def update_weights(gradients, weights):
  for g,w in zip(gradients, weights):
    w.assign_sub(g * learning_rate)

from tensorflow.keras import optimizers
optimizer = optimizers.SGD(learning_rate = 1e-3)

def update_weights(gradients, weights):
  optimizer.apply_gradients(zip(gradients, weights))


def fit(model, images, labels, epochs, batch_size = 128):
     for epoch_counter in range(epochs):
        print(f"Epoch {epoch_counter}")

        batch_generator = BatchGenerator(images, labels)
        for batch_counter in range(batch_generator.num_batches):
          images_batch, labels_batch = batch_generator.next()
          loss = one_training_step(model, images_batch, labels_batch)
          if batch_counter % 100 == 0:
            print(f"loss at batch {batch_counter}: {loss:.2f}")


In [57]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32") / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32") / 255
fit(model, train_images, train_labels, epochs=10, batch_size=128)

Epoch 0
loss at batch 0: 0.02
loss at batch 100: 0.02
loss at batch 200: 0.02
loss at batch 300: 0.03
loss at batch 400: 0.07
Epoch 1
loss at batch 0: 0.02
loss at batch 100: 0.02
loss at batch 200: 0.02
loss at batch 300: 0.03
loss at batch 400: 0.07
Epoch 2
loss at batch 0: 0.02
loss at batch 100: 0.02
loss at batch 200: 0.02
loss at batch 300: 0.03
loss at batch 400: 0.07
Epoch 3
loss at batch 0: 0.02
loss at batch 100: 0.02
loss at batch 200: 0.02
loss at batch 300: 0.03
loss at batch 400: 0.07
Epoch 4
loss at batch 0: 0.02
loss at batch 100: 0.02
loss at batch 200: 0.02
loss at batch 300: 0.03
loss at batch 400: 0.07
Epoch 5
loss at batch 0: 0.02
loss at batch 100: 0.02
loss at batch 200: 0.02
loss at batch 300: 0.03
loss at batch 400: 0.07
Epoch 6
loss at batch 0: 0.02
loss at batch 100: 0.02
loss at batch 200: 0.02
loss at batch 300: 0.02
loss at batch 400: 0.07
Epoch 7
loss at batch 0: 0.02
loss at batch 100: 0.02
loss at batch 200: 0.02
loss at batch 300: 0.02
loss at batch 40

In [68]:
predictions = model(test_images)

In [69]:
import numpy as np
predictions = predictions.numpy()

In [70]:
prediction_labels = np.argmax(predictions, axis = 1)

In [73]:
matches = prediction_labels == test_labels

In [75]:
print(f"accuracy: {matches.mean():.2f}")

accuracy: 0.98
